In [ ]:
from rdkit import Chem, DataStructs
from rdkit.Chem import Draw

In [62]:
import numpy as np
import os
import pandas as pd
from sklearn.model_selection import train_test_split
import json

In [65]:
with open('idx.json', 'w') as f:
    json.dump(train_test_split(list(range(1,101)), test_size=0.2, random_state=42), f)

In [60]:
a = np.array([1,0,0,0,1,1])
np.nonzero(a)[0].tolist()

[0, 4, 5]

In [66]:
with open('idx.json', 'r') as f:
    tr, tst = json.load(f)

tr, tst

([56,
  89,
  27,
  43,
  70,
  16,
  41,
  97,
  10,
  73,
  12,
  48,
  86,
  29,
  94,
  6,
  67,
  66,
  36,
  17,
  50,
  35,
  8,
  96,
  28,
  20,
  82,
  26,
  63,
  14,
  25,
  4,
  18,
  39,
  9,
  79,
  7,
  65,
  37,
  90,
  57,
  100,
  55,
  44,
  51,
  68,
  47,
  69,
  62,
  98,
  80,
  42,
  59,
  49,
  99,
  58,
  76,
  33,
  95,
  60,
  64,
  85,
  38,
  30,
  2,
  53,
  22,
  3,
  24,
  88,
  92,
  75,
  87,
  83,
  21,
  61,
  72,
  15,
  93,
  52],
 [84,
  54,
  71,
  46,
  45,
  40,
  23,
  81,
  11,
  1,
  19,
  31,
  74,
  34,
  91,
  5,
  77,
  78,
  13,
  32])

In [48]:
path = './docking/DS_data/'
files = sorted(os.listdir(path))
a = np.empty(0, dtype=float)

for i in range(10):
    loc_path = path + f'{i * 25}k/'
    print('Загрузка из ', loc_path)
    files = sorted(os.listdir(loc_path))
    if len(files) < 25:
        print('Alarm: ', loc_path)
    for file in files:
        a_new = np.load(loc_path + file, allow_pickle=True)
        a = np.concat([a, a_new])
        if a_new.shape[0] != 1000:
            print('Alarm: ', file)

a.dump('docking_scores_all.npy')

Загрузка из  ./docking/DS_data/0k/
Загрузка из  ./docking/DS_data/25k/
Загрузка из  ./docking/DS_data/50k/
Загрузка из  ./docking/DS_data/75k/
Загрузка из  ./docking/DS_data/100k/
Alarm:  ./docking/DS_data/100k/
Загрузка из  ./docking/DS_data/125k/
Загрузка из  ./docking/DS_data/150k/
Загрузка из  ./docking/DS_data/175k/
Загрузка из  ./docking/DS_data/200k/
Загрузка из  ./docking/DS_data/225k/
Alarm:  docking_scores_249000-249455.npy


In [21]:
a.shape[0] - len(smiles_list)

-10

In [ ]:
from envs.sascorer import calculateScore

file_path = os.path.join('./dataset/zinc250k/zinc250k.smi')
fp = open(file_path, 'r')
smiles_list = [smiles.strip() for smiles in fp]

sas = lambda sml: calculateScore(Chem.MolFromSmiles(sml))
sas_vec = np.vectorize(sas)

def tanimoto(sml):
    
    mol_dmnp = Chem.MolFromSmiles('CC1CCC(C2=C1C=CC(=C2)C)C(C)CCC(=O)O')
    fp_dmnp = Chem.AllChem.GetMorganFingerprint(mol_dmnp, 2)

    mol_sml = Chem.MolFromSmiles(sml)
    fp_sml = Chem.AllChem.GetMorganFingerprint(mol_sml, 2) # здесь возможно возникает то самое предупреждение с MorganFingerprint
    
    return DataStructs.TanimotoSimilarity(fp_dmnp, fp_sml) # здесь вставить свой dist

tanimoto_vec = np.vectorize(tanimoto)

ds = ...
sa = sas_vec(smiles_list)
td = tanimoto_vec(smiles_list)

In [ ]:
dset = pd.DataFrame({'SMILES': np.array(smiles_list), 'DS': ds, 'SA': sa, 'TD': td})

In [ ]:
dset.to_csv('tmp_docking_dataset.csv', index=False)

In [2]:
np.load('docking_scores_0-9.npy', allow_pickle=True)

array([-8.6, -8.4, -8.9, -8.1, -7.5, -4.8, -6.2, -8.4, -8.4, -6.4])

In [18]:
ds = np.load('docking_scores.npy', allow_pickle=True)
ds[ds != 0][797:798].min()

-9.8

У train №797 DS -9.8

In [2]:
X = np.load('./data_preprocessed/zinc250k/node_features.npy')
print('Nodes done')
A = np.load('./data_preprocessed/zinc250k/adj_features.npy')
print('Bonds done')

Nodes done
Bonds done


In [16]:
mol_sizes = np.load('./data_preprocessed/zinc1500k/mol_sizes.npy')

In [10]:
DMNP_mol = Chem.MolFromPDBFile("./docking/294-BD_AD_receptor_ligand_140.988_160.730_-16.038/294-BD_AD_receptor_ligand_140.988_160.730_-16.038.pdb")

In [11]:
DMNP_smiles = Chem.MolToSmiles(DMNP_mol)
DMNP_smiles

'CC1CCC2C(C)CCC(C(C)CCC(O)O)C2C1'

In [4]:
import time

In [2]:
import os
current_dir = os.getcwd()  # Текущая рабочая директория
parent_dir = os.path.dirname(current_dir)
file_path = os.path.join(parent_dir, 'title.txt')

In [3]:
current_dir, parent_dir, file_path

('q:\\Учеба\\Универ\\6 курс\\Диплом\\NF_mol_gen',
 'q:\\Учеба\\Универ\\6 курс\\Диплом',
 'q:\\Учеба\\Универ\\6 курс\\Диплом\\title.txt')

In [1]:
from rdkit import Chem
from rdkit.Chem import AllChem
import subprocess

# protein = Chem.MolFromPDBFile("./docking/294-BD_AD_receptor_ligand_140.988_160.730_-16.038/receptor.pdb")
# Chem.MolToPDBFile(protein, "receptor_rdkit.pdbqt")

def pdb_to_pdbqt_rdkit(input_pdb, output_pdbqt):
    """
    Конвертирует PDB в PDBQT с помощью RDKit (подготовка) и Open Babel (финальная конвертация).
    
    Параметры:
        input_pdb (str): Путь к входному PDB-файлу.
        output_pdbqt (str): Путь для сохранения PDBQT-файла.
    """
    # 1. Загрузка PDB в RDKit
    print(1)
    mol = Chem.MolFromPDBFile(input_pdb, removeHs=False)
    if mol is None:
        raise ValueError("Не удалось загрузить PDB-файл. Проверьте его целостность.")

    # 2. Добавление водородов (если их нет)
    print(2)
    mol = Chem.AddHs(mol, addCoords=True)

    # 3. Оптимизация геометрии (MMFF94 или UFF)
    print(3)
    try:
        AllChem.MMFFOptimizeMolecule(mol)  # MMFF94
    except:
        AllChem.UFFOptimizeMolecule(mol)  # Fallback на UFF

    # 4. Сохраняем во временный PDB-файл (RDKit не поддерживает PDBQT)
    print(4)
    temp_pdb = "temp_rdkit.pdb"
    Chem.MolToPDBFile(mol, temp_pdb)

    # 5. Конвертируем PDB → PDBQT через Open Babel
    print(5)
    obabel_cmd = f"obabel {temp_pdb} -O {output_pdbqt} -xh --partialcharge gasteiger"
    subprocess.run(obabel_cmd, shell=True, check=True)

    print(f"Файл сохранен: {output_pdbqt}")

# Пример использования
# pdb_to_pdbqt_rdkit("input.pdb", "output.pdbqt")

In [2]:
pdb_to_pdbqt_rdkit('./docking/294-BD_AD_receptor_ligand_140.988_160.730_-16.038/receptor.pdb', './docking/receptor_auto.pdbqt')

1
2
3
4
5
Файл сохранен: ./docking/receptor_auto.pdbqt


In [4]:
from preprocess import Zinc_Processor, SmilesPreprocessor

In [ ]:
sp = SmilesPreprocessor(add_Hs=False, kekulize=True, max_atoms=38, max_size=40)
x, A, sz, _ = sp.process('CC(C)(C)c1ccc2occ(CC(=O)Nc3ccccc3F)c2c1')

In [20]:
np.load('./docking/Марк/zinc_DS/2025-04-12_16-29-13/docking_scores_0-9.npy', allow_pickle=True)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
zp = Zinc_Processor('DMNP_read.txt', './my_scripts')

sl:  ['CC1CCC(C2=C1C=CC(=C2)C)C(C)CCC(=O)O']


100%|██████████| 1/1 [00:02<00:00,  3.00s/it]

total number of valid molecule in dataset: 1
try to save
./my_scripts
saving node/adj feature...
shape of node feature: (1, 50)
shape of adj features: (1, 3, 50, 50)
shape of mol sizes: (1,)
save config
saving config...
{'atom_list': [6, 7, 8, 9, 15, 16, 17, 35, 53, 0], 'node_dim': 10, 'max_size': 50, 'bond_dim': 4}


In [17]:
np.concat([np.empty(0), np.load(path + file, allow_pickle=True)])

array([-7.8, -8. , -3.7, -6.5, -8.2, -7.1, -6.8, -6.8, -6.6, -7. ])

In [44]:
np.load('./docking/DS_data/25k/small/docking_scores_27630-27639.npy', allow_pickle=True)[:1000] == np.load('./docking/DS_data/25k/small/rdy/docking_scores_27000-27999.npy', allow_pickle=True)[630:640]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [43]:
path = './docking/DS_data/25k/small/'
files = sorted(os.listdir(path))
a = np.empty(0, dtype=float)
for i, file in enumerate(files):
    a_new = np.load(path + file, allow_pickle=True)
    a = np.concat([a, a_new])
    if (i + 1) % 100 == 0:
        file_name = f'docking_scores_{25000 + (i - 99) * 10}-{25000 + i * 10 + 9}.npy'
        a.dump(path + 'rdy/' + file_name)
        print('Size of ', file_name, ': ', a.shape[0])
        a = np.empty(0)

Size of  docking_scores_25000-25999.npy :  1000
Size of  docking_scores_26000-26999.npy :  1000
Size of  docking_scores_27000-27999.npy :  1000
Size of  docking_scores_28000-28999.npy :  1000
Size of  docking_scores_29000-29999.npy :  1000
Size of  docking_scores_30000-30999.npy :  1000
Size of  docking_scores_31000-31999.npy :  1000
Size of  docking_scores_32000-32999.npy :  1000
Size of  docking_scores_33000-33999.npy :  1000
Size of  docking_scores_34000-34999.npy :  1000
Size of  docking_scores_35000-35999.npy :  1000
Size of  docking_scores_36000-36999.npy :  1000


PermissionError: [Errno 13] Permission denied: './docking/DS_data/25k/small/rdy'

In [33]:
for i in range(5):
    with open('mse.txt', 'a') as f:
        f.write(f'{i},')

In [23]:
from utils import valid_mol

<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for class boost::shared_ptr<class RDKit::FilterHierarchyMatcher> already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for class boost::shared_ptr<class RDKit::FilterCatalogEntry> already registered; second conversion method ignored.


In [7]:
import moses
import pandas as pd

In [2]:
train = moses.get_dataset('train')
test = moses.get_dataset('test')
test_scaffolds = moses.get_dataset('test_scaffolds')

In [2]:
from torch.utils.data import DataLoader
from moses import CharVocab, StringDataset

train = moses.get_dataset('train')
vocab = CharVocab.from_data(train)
train_dataset = StringDataset(vocab, train)
train_dataloader = DataLoader(
    train_dataset, batch_size=512,
    shuffle=True, collate_fn=train_dataset.default_collate
)

In [9]:
pd.Series(train)#.to_csv('zinc1500K.smi', index=False)

0            CCCS(=O)c1ccc2[nH]c(=NC(=O)OC)[nH]c2c1
1              CC(C)(C)C(=O)C(Oc1ccc(Cl)cc1)n1ccnc1
2               Cc1c(Cl)cccc1Nc1ncccc1C(=O)OCC(O)CO
3                  Cn1cnc2c1c(=O)n(CC(O)CO)c(=O)n2C
4                    CC1Oc2ccc(Cl)cc2N(CC(O)CO)C1=O
                             ...                   
1584658                        N#Cc1c(Br)cnc(N)c1Br
1584659          COC(=O)c1cc(CNC(=O)OC(C)(C)C)ccc1C
1584660                      NC(=O)c1ccc2ccccc2c1Br
1584661    CC(=O)Nc1cccc(-c2nc3cc(C)ccc3[nH]c2=O)c1
1584662     CC(NC(=O)OC(C)(C)C)c1nc(CO)nn1Cc1ccccc1
Length: 1584663, dtype: object

In [13]:
for i, (with_bos, with_eos, lengths) in enumerate(train_dataloader):
    print(with_bos.shape, with_eos.shape, len(lengths))
    if i == 2:
        break

torch.Size([50, 512]) torch.Size([50, 512]) 512
torch.Size([49, 512]) torch.Size([49, 512]) 512
torch.Size([52, 512]) torch.Size([52, 512]) 512


In [5]:
type(train), type(vocab), type(train_dataset), type(train_dataloader)

(numpy.ndarray,
 moses.utils.CharVocab,
 moses.utils.StringDataset,
 torch.utils.data.dataloader.DataLoader)

In [8]:
train.shape

(1584663,)

In [ ]:
from torch.utils.data import DataLoader
from moses import CharVocab, StringDataset

train = moses.get_dataset('train')
vocab = CharVocab.from_data(train)
train_dataset = StringDataset(vocab, train)
train_dataloader = DataLoader(
    train_dataset, batch_size=512,
    shuffle=True, collate_fn=train_dataset.default_collate
)

for with_bos, with_eos, lengths in train_dataloader:
    ...

In [2]:
from envs import molecular_metrics as mm

In [37]:
mm.MolecularMetrics._compute_SAS(mol)

1.5149307387756714

In [6]:
smiles_list[18]

'Cc1c(NC(=O)CSc2nc3sc4c(c3c(=O)[nH]2)CCCC4)c(=O)n(-c2ccccc2)n1C'

In [10]:
from rdkit import Chem
from envs.sascorer import calculateScore

smiles1 = "CC1CCC(C2=C1C=CC(=C2)C)C(C)CCC(=O)O"
mol1 = Chem.MolFromSmiles(smiles1)
sa_score1 = calculateScore(mol1)
print(f"SA Score для {smiles1}: {sa_score1}")

smiles2 = "Cc1c(NC(=O)CSc2nc3sc4c(c3c(=O)[nH]2)CCCC4)c(=O)n(-c2ccccc2)n1C"
mol2 = Chem.MolFromSmiles(smiles2)
sa_score2 = calculateScore(mol2)
print(f"SA Score для {smiles2}: {sa_score2}")

SA Score для CC1CCC(C2=C1C=CC(=C2)C)C(C)CCC(=O)O: 3.3559737244164882
SA Score для Cc1c(NC(=O)CSc2nc3sc4c(c3c(=O)[nH]2)CCCC4)c(=O)n(-c2ccccc2)n1C: 2.62217770660925


In [15]:
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem
import rdkit
import rdkit.Chem

fp1 = AllChem.GetMorganFingerprint(mol1, 2)
fp2 = AllChem.GetMorganFingerprint(mol2, 2)

sim = DataStructs.TanimotoSimilarity(fp1, fp2)
print('Танимото схожесть: {}'.format(sim))

Танимото схожесть: 0.13178294573643412


In [5]:
fp = open('./dataset/zinc250k/zinc250k.smi', 'r')
smiles_list = [smiles.strip() for smiles in fp]

In [9]:
valid_mol(mol)

In [7]:
mol = Chem.MolFromSmiles('C1=CC=CC=C1')
sml = Chem.MolToSmiles(mol)
print(sml)

c1ccccc1


In [ ]:
from rdkit import Chem
from rdkit.Chem import Draw

# Пример SMILES
smiles = 'CC(=O)O'  # бензол

# Создание молекулы из SMILES
mol = Chem.MolFromSmiles(smiles)

# Рисование молекулы и сохранение изображения
img = Draw.MolToFile(mol, 'molecule.png')
